### ISSUE TITLE
Unable to handle artists with slashes

### ISSUE THREAD

**Issue by JonRheaSr** [SharieRhea/TrackTagger#3]
The script failed when it tried to create a file for the artist "AC/DC" presumably because it contains an un-escaped forward slash

**Comment by SharieRhea** [comment]
Hmm, this presents an interesting challenge because filenames in Linux cannot contain `/`.

Possible solutions:
1. Simply remove the slash when creating filenames. For example `T.N.T - AC/DC.mp3` becomes `T.N.T - ACDC.mp3`
2. Replace the slash with some other character, like `.`. For example `T.N.T - AC/DC.mp3` becomes `T.N.T - AC.DC.mp3`

Also should note that there are more reserved characters for other operating systems. Windows does not allow `< : " / \ | ? *`. These should be handled as well.

Thoughts?
